services:
  backend:
    build:
      context: ./app
      dockerfile: DockerFile
    env_file:
      - .env
    volumes:
      - .:/app
      - chroma_data:/app/.chroma_db
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./smart-librarian-ui
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./smart-librarian-ui:/app
      - /app/node_modules # cache for node-modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  chroma_data: